# Generated by Django 5.2.13 on 2026-05-03 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grindingtransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grinding_transactions', to='mill.customer'),
        ),
        migrations.AlterField(
            model_name='grindingtransaction',
            name='grain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grinding_name', to='mill.ratecard'),
        ),
    ]
