# Generated by Django 5.2.13 on 2026-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0002_alter_grindingtransaction_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='buyback_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
