from rest_framework import viewsets
from .models import Customer,RateCard,GrindingTransaction,LedgerEntry,Expense,StockItem,StockMovement,Employee
from .serializers import CustomerSerializer,RateCardSerializer,GrindingTransactionSerializer,LedgerEntrySerializer,ExpenseSerializer,StockItemSerializer,StockMovementSerializer,EmployeeSerializer
class CustomerViewSet(viewsets.ModelViewSet): queryset=Customer.objects.all(); serializer_class=CustomerSerializer
class RateCardViewSet(viewsets.ModelViewSet): queryset=RateCard.objects.all(); serializer_class=RateCardSerializer
class GrindingTransactionViewSet(viewsets.ModelViewSet): queryset=GrindingTransaction.objects.select_related('customer','grain_name'); serializer_class=GrindingTransactionSerializer
class LedgerEntryViewSet(viewsets.ModelViewSet): queryset=LedgerEntry.objects.select_related('customer'); serializer_class=LedgerEntrySerializer
class ExpenseViewSet(viewsets.ModelViewSet): queryset=Expense.objects.all(); serializer_class=ExpenseSerializer
class StockItemViewSet(viewsets.ModelViewSet): queryset=StockItem.objects.all(); serializer_class=StockItemSerializer
class StockMovementViewSet(viewsets.ModelViewSet): queryset=StockMovement.objects.select_related('item'); serializer_class=StockMovementSerializer
class EmployeeViewSet(viewsets.ModelViewSet): queryset=Employee.objects.all(); serializer_class=EmployeeSerializer
